name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove bundled Sparkle duplicate
        run: |
          rm -rf "Sparkle-for-Swift-Package-Manager"

      - name: Resolve packages
        run: |
          xcodebuild \
          -resolvePackageDependencies \
          -project "Apple Music Cracked Edition.xcodeproj"

      - name: Clean build
        run: |
          xcodebuild \
          -project "Apple Music Cracked Edition.xcodeproj" \
          -scheme "Apple Music Cracked Edition" \
          clean

      - name: Build
        run: |
          xcodebuild \
          -project "Apple Music Cracked Edition.xcodeproj" \
          -scheme "Apple Music Cracked Edition" \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY="" \
          build

      - name: Find app
        run: |
          find ~/Library/Developer/Xcode/DerivedData -name "*.app"

      - name: Package
        run: |
          mkdir build
          cp -R "$(find ~/Library/Developer/Xcode/DerivedData -name 'Apple Music Cracked Edition.app' | head -n 1)" build/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Apple-Music-Cracked-Edition-App
          path: build/
